### ISSUE TITLE
Error when loading into BigQuery

### ISSUE THREAD

**Issue by flankerad** [bmizhen/rec-avro#2]
Hi new to Avro, I was testing out rec-avro. Uploading avro files written by rec-avro into Google BigQuery, getting the following error:

` Unsupported empty struct type for field '_.map_union_null_boolean_int_long_float_double_string_bytes_rec_avro_rec_object_value.value.rec_avro_rec_object_value._' `

This seems to the metadata field. Would be great if I can get some idea as to what is actually happening. Thanks

**Comment by bmizhen-exos** [comment]
I don't have experience with GBQ, but there is a possibility that this is not rec-avro related. See https://stackoverflow.com/questions/57013758/google-bigquery-load-from-gcs-fails-with-error-unsupported-empty-struct-type-for

Can you post the entire error message? any stack traces?

**Comment by bmizhen-exos** [comment]
Rec avro does allow empty nested datastructures, this is by design. It is possible that GBQ does not like this. If that is the case you would have to create an explicit avro schema.
