### ISSUE TITLE
how to send generated avro file to producer

### ISSUE THREAD

**Issue by vbpatel73** [bmizhen/rec-avro#5]
Hi I can create avro file but how i can send to producer?

**Comment by bmizhen** [comment]
Not clear what you are trying to accomplish. A code sample would help.

**Comment by vbpatel73** [comment]
`from fastavro import writer, reader, schema
from rec_avro import to_rec_avro_destructive, from_rec_avro_destructive, rec_avro_schema
 
def json_objects():
    return [{
            "ospId": "601945b2-213c-49f2-bfa0-1aa14aabed95",
            "eventHeader": {
                "id": "00021908812681",
                "type": "purchaseOrderPlaced",
                "time": 1598267669249,
                "source": "purchase-order-service"
                    }
                    }]
 
# For efficiency, to_rec_avro_destructive() destroys rec, and reuses it's
# data structures to construct avro_objects 
avro_objects = (to_rec_avro_destructive(rec) for rec in json_objects())

# store records in avro
with open('json_in_avro.avro', 'wb') as f_out:
    writer(f_out, schema.parse_schema(rec_avro_schema()), avro_objects)
 
#load records from avro
with open('json_in_avro.avro', 'rb') as f_in:
    # For efficiency, from_rec_avro_destructive(rec) destroys rec, and 
    # reuses it's data structures to construct it's output
    loaded_json = [from_rec_avro_destructive(rec) for rec in reader(f_in)]
 
assert loaded_json == json_objects()`

with this code, i can generate avro message but how i can send to kafka with producer?

**Comment by bmizhen** [comment]
https://www.google.com/search?q=how+to+send+json+to+kafka+topic+python
